In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
house_data = pd.read_csv('../data/raw/Property_Assessment_Data__Historical_.csv')

c:\users\mitch\documents\data science side projects\edmonton property dashboard\prop_env\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (2,17,19) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
#current year as of oct 2021 -> accessed oct 27/2021
current_house_data = pd.read_csv('../data/raw/Property_Assessment_Data__Current_Calendar_Year_.csv')

In [4]:
current_house_data.head()

,Account Number,Suite,House Number,Street Name,Garage,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Latitude,Longitude,Point Location,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Assessment Class 1,Assessment Class 2,Assessment Class 3
0,10177229,NaN,NaN,NaN,N,6213.0,SUMMERSIDE,Karhiio Ward,52000,53.420646,-113.475389,POINT (-113.4753890817257 53.42064580930636),100,NaN,NaN,COMMERCIAL,NaN,NaN
1,1194422,NaN,15613.0,83 STREET NW,N,2050.0,BELLE RIVE,tastawiyiniwak Ward,242000,53.616851,-113.467976,POINT (-113.46797578947897 53.61685142883479),100,NaN,NaN,RESIDENTIAL,NaN,NaN
2,1034222,NaN,10626.0,161 AVENUE NW,Y,3040.0,BEAUMARIS,tastawiyiniwak Ward,411500,53.620471,-113.507630,POINT (-113.50763003337708 53.620471257753714),100,NaN,NaN,RESIDENTIAL,NaN,NaN
3,1114768,NaN,14915.0,76 AVENUE NW,Y,4430.0,RIO TERRACE,sipiwiyiniwak Ward,431500,53.508643,-113.579289,POINT (-113.57928868418604 53.508643477515854),100,NaN,NaN,RESIDENTIAL,NaN,NaN
4,1012285,NaN,564.0,WOLF WILLOW ROAD NW,Y,4610.0,WESTRIDGE,sipiwiyiniwak Ward,686500,53.507641,-113.603755,POINT (-113.60375458739135 53.507641466024275),100,NaN,NaN,RESIDENTIAL,NaN,NaN

# House Data EDA

In [5]:
house_data.head()

,Account Number,Assessment Year,Suite,House Number,Street Name,Legal Description,Latitude,Longitude,Point Location,Neighbourhood,...,Garage,Zoning,Lot Size,Assessed Value,Assessment Class 1,Assessment Class % 1,Assessment Class 2,Assessment Class % 2,Assessment Class 3,Assessment Class % 3
0,1068451,2015,NaN,4007.0,SAVARYN DRIVE SW,SW 22-51-24-4,NaN,NaN,NaN,SUMMERSIDE,...,N,RPL,109314.321,7597000.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
1,1152594,2012,NaN,17310.0,97 STREET NW,NaN,NaN,NaN,NaN,ELSINORE,...,N,AG,0.000,12500.0,COMMERCIAL,100.0,NaN,NaN,NaN,NaN
2,1153568,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BATTERY OIL FIELDS,...,N,AG,0.000,88000.0,COMMERCIAL,100.0,NaN,NaN,NaN,NaN
3,1153626,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BATTERY OIL FIELDS,...,N,AG,0.000,0.0,COMMERCIAL,100.0,NaN,NaN,NaN,NaN
4,1248590,2016,NaN,NaN,NaN,NW 3-52-25-4,NaN,NaN,NaN,TERWILLEGAR AREA,...,N,A,10000.000,49500.0,COMMERCIAL,100.0,NaN,NaN,NaN,NaN

In [6]:
house_data.columns

Index(['Account Number', 'Assessment Year', 'Suite', 'House Number',
       'Street Name', 'Legal Description', 'Latitude', 'Longitude',
       'Point Location', 'Neighbourhood', 'Actual Year Built', 'Garage',
       'Zoning', 'Lot Size', 'Assessed Value', 'Assessment Class 1',
       'Assessment Class % 1', 'Assessment Class 2', 'Assessment Class % 2',
       'Assessment Class 3', 'Assessment Class % 3'],
      dtype='object')

In [7]:
house_data.shape

(3384820, 21)

In [8]:
house_data['Account Number'].is_unique

False

Some properties have multiple assessments

In [9]:
house_data['Assessment Class 1'].unique()

array(['RESIDENTIAL', 'COMMERCIAL', nan, 'FARMLAND', 'OTHER RESIDENTIAL',
       'NONRES MUNICIPAL/RES EDUCATION'], dtype=object)

In [10]:
house_data['Assessment Class 2'].unique()

array([nan, 'RESIDENTIAL', 'FARMLAND', 'COMMERCIAL', 'OTHER RESIDENTIAL',
       'NONRES MUNICIPAL/RES EDUCATION'], dtype=object)

In [11]:
house_data['Assessment Class 3'].unique()

array([nan, 'FARMLAND', 'COMMERCIAL', 'RESIDENTIAL', 'OTHER RESIDENTIAL',
       'NONRES MUNICIPAL/RES EDUCATION'], dtype=object)

In [12]:
house_data[~house_data['Assessment Class 2'].isna()]

,Account Number,Assessment Year,Suite,House Number,Street Name,Legal Description,Latitude,Longitude,Point Location,Neighbourhood,...,Garage,Zoning,Lot Size,Assessed Value,Assessment Class 1,Assessment Class % 1,Assessment Class 2,Assessment Class % 2,Assessment Class 3,Assessment Class % 3
718,1008770,2015,NaN,10640.0,180 STREET NW,Plan: 7214KS Lot: 2,53.55080,-113.63436,POINT (-113.63436 53.5508),WILSON INDUSTRIAL,...,N,IM,64683.449,1779000.0,COMMERCIAL,1.0,RESIDENTIAL,99.0,NaN,NaN
807,1001544,2013,NaN,2703.0,184 STREET NW,SE 4-52-25-4,53.45936,-113.62259,POINT (-113.62259 53.45936),RURAL WEST,...,N,A,212866.582,552000.0,RESIDENTIAL,99.0,FARMLAND,1.0,NaN,NaN
2272,1002294,2013,NaN,2304.0,184 STREET NW,SE 5-52-25-4,53.45754,-113.64299,POINT (-113.64299 53.45754),RURAL WEST,...,N,AG,303777.470,96500.0,RESIDENTIAL,24.0,FARMLAND,76.0,NaN,NaN
3511,1002328,2019,NaN,18904.0,23 AVENUE NW,SE 5-52-25-4,53.45754,-113.64905,POINT (-113.64905 53.45754),THE UPLANDS,...,N,AG,303770.525,2159000.0,RESIDENTIAL,99.0,FARMLAND,1.0,NaN,NaN
3543,1001361,2012,NaN,2005.0,184 STREET NW,NE 33-51-25-4 / NW 33-51-25-4,53.45081,-113.63449,POINT (-113.63449 53.45081),RURAL WEST,...,N,AG,383887.175,760500.0,RESIDENTIAL,92.0,FARMLAND,8.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3382038,10945385,2020,NaN,310.0,PARSONS ROAD SW,Plan: 1922859 Block: 2 Lot: 2,53.43101,-113.48145,POINT (-113.48145 53.43101),ELLERSLIE INDUSTRIAL,...,N,EIB,21460.293,2436500.0,COMMERCIAL,76.0,FARMLAND,23.0,FARMLAND,1.0
3382764,10945386,2020,NaN,420.0,PARSONS ROAD SW,Plan: 1922859 Block: 2 Lot: 3,53.42993,-113.48149,POINT (-113.48149 53.42993),ELLERSLIE INDUSTRIAL,...,N,EIB,15775.722,2436000.0,COMMERCIAL,68.0,FARMLAND,31.0,FARMLAND,1.0
3382790,10931838,2020,NaN,51012.0,HIGHWAY 2 SERVICE ROAD 2 SW,NaN,53.36892,-113.53245,POINT (-113.53245 53.36892),EDMONTON SOUTH CENTRAL,...,Y,AES,156856.467,660500.0,RESIDENTIAL,93.0,COMMERCIAL,4.0,FARMLAND,2.0
3383112,10928855,2020,NaN,6415.0,200 STREET SW,Plan: 1920354 Block: 1 Lot: 5,53.37485,-113.66125,POINT (-113.66125 53.37485),EDMONTON SOUTH WEST,...,Y,AES,50029.309,512500.0,RESIDENTIAL,99.0,FARMLAND,1.0,NaN,NaN
3384610,10951325,2020,NaN,10615.0,82 AVENUE NW,Plan: I Block: 64 Lot: 5 / Plan: I Block: 6...,53.51777,-113.50424,POINT (-113.50424 53.51777),QUEEN ALEXANDRA,...,N,DC1,3234.367,7886500.0,OTHER RESIDENTIAL,80.0,COMMERCIAL,20.0,NaN,NaN

Assessment class looks to classify if the property is a certain type of property (residential, commercial, etc.). Some properties can consist of multiple classes (eg. an apartment building with businesses on the main floor).

For this project, focused only on residential properties

In [13]:
resi_house_data = house_data[(house_data['Assessment Class 1'] == 'RESIDENTIAL') & (house_data['Assessment Class % 1'] == 100)]

In [14]:
resi_house_data

,Account Number,Assessment Year,Suite,House Number,Street Name,Legal Description,Latitude,Longitude,Point Location,Neighbourhood,...,Garage,Zoning,Lot Size,Assessed Value,Assessment Class 1,Assessment Class % 1,Assessment Class 2,Assessment Class % 2,Assessment Class 3,Assessment Class % 3
0,1068451,2015,NaN,4007.0,SAVARYN DRIVE SW,SW 22-51-24-4,NaN,NaN,NaN,SUMMERSIDE,...,N,RPL,109314.321,7597000.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
7,1650860,2014,NaN,NaN,NaN,Plan: 3782RS Block: 1 Lot: 30U,53.51545,-113.61627,POINT (-113.61627 53.51545),THORNCLIFF,...,N,RF1,118.072,0.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
9,2914836,2018,NaN,13004.0,115 AVENUE NW,Plan: 1568HW Block: 4 Lot: 21,NaN,NaN,NaN,INGLEWOOD,...,Y,RF3,490.277,358500.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
14,3169893,2019,NaN,2503.0,101 STREET SW,Plan: 8721140 Block: E,NaN,NaN,NaN,ELLERSLIE INDUSTRIAL,...,N,AGI,49452.501,244500.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
28,9947689,2013,NaN,35.0,ELSINORE PLACE NW,NE 5-54-24-4,NaN,NaN,NaN,ELSINORE,...,N,RF1,711.319,55500.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3384813,10937630,2020,NaN,3703.0,2 STREET NW,Plan: 1922185 Block: 6 Lot: 4,53.47286,-113.34529,POINT (-113.34529 53.47286),MAPLE,...,N,RMD,334.741,74500.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
3384814,10961829,2020,43,1391.0,STARLING DRIVE NW,Plan: 1621919 Unit: 56,53.59888,-113.65292,POINT (-113.65292 53.59888),STARLING,...,Y,RA7,205.444,281500.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
3384816,10954527,2020,NaN,NaN,NaN,Plan: 1923211 Unit: 87A,53.51841,-113.50710,POINT (-113.5071 53.51841),GARNEAU,...,N,DC1,5.849,10000.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
3384817,10954448,2020,116,10728.0,82 AVENUE NW,Plan: 1923211 Unit: 7A,53.51841,-113.50710,POINT (-113.5071 53.51841),GARNEAU,...,N,DC1,63.649,408000.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN
3384819,10943939,2020,NaN,5242.0,23 AVENUE SW,Plan: 1922598 Block: 11 Lot: 33,53.41254,-113.42280,POINT (-113.4228 53.41254),WALKER,...,N,DC1,340.353,146500.0,RESIDENTIAL,100.0,NaN,NaN,NaN,NaN

In [15]:
pd.set_option('float_format', '{:f}'.format)
resi_house_data['Assessed Value'].describe()

count    3159043.000000
mean      316251.180583
std       267990.034578
min            0.000000
25%       188500.000000
50%       315500.000000
75%       407500.000000
max     30081500.000000
Name: Assessed Value, dtype: float64

In [16]:
resi_house_data['Lot Size'].describe()

count   3133955.000000
mean        575.083918
std        6655.532823
min           0.000000
25%         116.873000
50%         386.330000
75%         568.710000
max      692660.676000
Name: Lot Size, dtype: float64

## Year to Year Stats

In [17]:
resi_house_data['Assessment Year'].unique()

array([2015, 2014, 2018, 2019, 2013, 2016, 2020, 2017, 2012], dtype=int64)

Assessment years range from 2012-2020

In [18]:
year_list = resi_house_data['Assessment Year'].unique()
year_list = np.sort(year_list)

In [19]:
def stat_per_year(df, stat_column_name, year_list):
    stat_avg_list = []
    for year in year_list:
        year_mask = df[df['Assessment Year'] == year]
        stat_avg = year_mask[stat_column_name].mean()
        stat_avg_list.append(stat_avg)
    return stat_avg_list

In [20]:
stat_per_year(resi_house_data, 'Assessed Value', year_list)

[297938.80247374997,
 303019.2879716732,
 310056.77121176035,
 328291.5306077863,
 329221.1052836597,
 320403.051073206,
 320276.01980874134,
 321294.3759825549,
 312000.6391176764]

In [21]:
stat_per_year(resi_house_data, 'Lot Size', year_list)

[498.5808104018645,
 505.42830940270926,
 645.5294803751644,
 640.7431069573416,
 617.4179594250094,
 601.7617172917338,
 576.3431685178066,
 552.4317688838518,
 532.055321387008]

### incorporate wards into dataset

In [22]:
current_house_data['Ward'].value_counts()

O-day'min Ward                38310
Ipiihkoohkanipiaohtsi Ward    36914
Métis Ward                    36510
pihêsiwin Ward                36353
sipiwiyiniwak Ward            36152
Karhiio Ward                  35373
Nakota Isga Ward              34355
Dene Ward                     33862
Anirniq Ward                  33571
papastew Ward                 31793
tastawiyiniwak Ward           29961
Sspomitapi Ward               28006
Name: Ward, dtype: int64

In [23]:
ward_mask = current_house_data[['Ward','Neighbourhood']]
ward_mask

                              Ward   Neighbourhood
0                     Karhiio Ward      SUMMERSIDE
1              tastawiyiniwak Ward      BELLE RIVE
2              tastawiyiniwak Ward       BEAUMARIS
3               sipiwiyiniwak Ward     RIO TERRACE
4               sipiwiyiniwak Ward       WESTRIDGE
...                            ...             ...
411161  Ipiihkoohkanipiaohtsi Ward  CHAPPELLE AREA
411162  Ipiihkoohkanipiaohtsi Ward        CAVANAGH
411163            Nakota Isga Ward   WEBBER GREENS
411164          sipiwiyiniwak Ward        EDGEMONT
411165            Nakota Isga Ward        STARLING

[411166 rows x 2 columns]

In [24]:
ward_mask.groupby('Ward')['Neighbourhood'].unique()

Ward
Anirniq Ward                  [HAGMANN ESTATE INDUSTRIAL, GAGNON ESTATE INDU...
Dene Ward                     [RURAL NORTH EAST HORSE HILL, FRASER, BANNERMA...
Ipiihkoohkanipiaohtsi Ward    [SKYRATTLER, KEHEEWIN, BEARSPAW, BLUE QUILL, R...
Karhiio Ward                  [SUMMERSIDE, MEYONOHK, SAKAW, ELLERSLIE, MEYOK...
Métis Ward                    [EASTGATE BUSINESS PARK, WEIR INDUSTRIAL, MONT...
Nakota Isga Ward              [GLENWOOD, WEST JASPER PLACE, ALDERGROVE, WINT...
O-day'min Ward                [OLIVER, CENTRAL MCDOUGALL, WESTMOUNT, QUEEN M...
Sspomitapi Ward               [MAPLE RIDGE, BISSET, WEINLOS, POLLARD MEADOWS...
papastew Ward                 [STRATHCONA, QUEEN ALEXANDRA, GARNEAU, EMPIRE ...
pihêsiwin Ward                [RAMSAY HEIGHTS, HENDERSON ESTATES, RHATIGAN R...
sipiwiyiniwak Ward            [RIO TERRACE, WESTRIDGE, MEADOWLARK PARK, JASP...
tastawiyiniwak Ward           [BELLE RIVE, BEAUMARIS, LAGO LINDO, KILKENNY, ...
Name: Neighbourhood, dtype: object

In [25]:
ward_dict = ward_mask.groupby('Ward')['Neighbourhood'].unique().to_dict()

In [26]:
ward_dict = {k:v.tolist() for k,v in ward_dict.items()}

In [27]:
ward_dict

{'Anirniq Ward': ['HAGMANN ESTATE INDUSTRIAL',
  'GAGNON ESTATE INDUSTRIAL',
  'MISTATIM INDUSTRIAL',
  'DUNLUCE',
  'LAUDERDALE',
  'CARLISLE',
  'PRINCE CHARLES',
  'MITCHELL INDUSTRIAL',
  'DOVERCOURT',
  'GOODRIDGE CORNERS',
  'INGLEWOOD',
  'CARLTON',
  'ROSSLYN',
  'RAMPART INDUSTRIAL',
  'HIGH PARK INDUSTRIAL',
  'ANTHONY HENDAY MISTATIM',
  'CALDER',
  'GARSIDE INDUSTRIAL',
  'CUMBERLAND',
  'ANTHONY HENDAY RAMPART',
  'PEMBINA',
  'KENSINGTON',
  'HUFF BREMNER ESTATE INDUSTRIAL',
  'CANOSSA',
  'RAPPERSWILL',
  'WOODCROFT',
  'BONAVENTURE INDUSTRIAL',
  'BROWN INDUSTRIAL',
  'ATHLONE',
  'YELLOWHEAD CORRIDOR WEST',
  'BARANOW',
  'SHERBROOKE',
  'DOMINION INDUSTRIAL',
  'WELLINGTON',
  'MCARTHUR INDUSTRIAL',
  'ALBANY',
  'CAERNARVON',
  'OXFORD',
  'GRIESBACH',
  'HUDSON'],
 'Dene Ward': ['RURAL NORTH EAST HORSE HILL',
  'FRASER',
  'BANNERMAN',
  'HAIRSINE',
  'BELVEDERE',
  'CLOVER BAR AREA',
  'CASSELMAN',
  'EDMONTON ENERGY AND TECHNOLOGY PARK',
  'RURAL NORTH EAST SOUTH STURGEON',
  'KIRKNESS',
  'ANTHONY HENDAY HORSE HILL',
  'YORK',
  'EBBERS',
  'HOMESTEADER',
  'MARQUIS',
  'GORMAN',
  'KENNEDALE INDUSTRIAL',
  'CY BECKER',
  'MCCONACHIE AREA',
  'BRINTNELL',
  'ANTHONY HENDAY ENERGY PARK',
  'OVERLANDERS',
  'EVERGREEN',
  'ANTHONY HENDAY CLAREVIEW',
  'MCLEOD',
  'MATT BERRY',
  'HOLLICK-KENYON',
  'KERNOHAN',
  'RIVER VALLEY HERMITAGE',
  'CLAREVIEW TOWN CENTRE',
  'BELMONT',
  'CANON RIDGE',
  'SIFTON PARK',
  'MILLER'],
 'Ipiihkoohkanipiaohtsi Ward': ['SKYRATTLER',
  'KEHEEWIN',
  'BEARSPAW',
  'BLUE QUILL',
  'RICHFORD',
  'SWEET GRASS',
  'ERMINESKIN',
  'CHAPPELLE AREA',
  'GLENRIDDING RAVINE',
  'HAYS RIDGE AREA',
  'STEINHAUER',
  'CAVANAGH',
  'HERITAGE VALLEY TOWN CENTRE AREA',
  'HERITAGE VALLEY AREA',
  'CASHMAN',
  'ALLARD',
  'BLACKBURNE',
  'PAISLEY',
  'TWIN BROOKS',
  'DESROCHERS AREA',
  'ANTHONY HENDAY SOUTH BLACKBURNE',
  'GRAYDON HILL',
  'BLACKMUD CREEK RAVINE',
  'BLUE QUILL ESTATES',
  'ANTHONY HENDAY SOUTH',
  'MACEWAN',
  'RUTHERFORD',
  'BLACKMUD CREEK',
  'CALLAGHAN',
  'EDMONTON SOUTH CENTRAL'],
 'Karhiio Ward': ['SUMMERSIDE',
  'MEYONOHK',
  'SAKAW',
  'ELLERSLIE',
  'MEYOKUMIN',
  'HILLVIEW',
  'ROPER INDUSTRIAL',
  'TIPASKAN',
  'KAMEYOSEK',
  'STRATHCONA INDUSTRIAL PARK',
  'ELLERSLIE INDUSTRIAL',
  'EDMONTON RESEARCH AND DEVELOPMENT PARK',
  'PARSONS INDUSTRIAL',
  'THE ORCHARDS AT ELLERSLIE',
  'MENISA',
  'PAPASCHASE INDUSTRIAL',
  'TAWA',
  'MATTSON',
  'MCINTYRE INDUSTRIAL',
  'CHARLESWORTH',
  'SOUTH EDMONTON COMMON',
  'GREENVIEW',
  'SATOO',
  'RICHFIELD',
  'MILL WOODS PARK',
  'CALGARY TRAIL SOUTH',
  'MICHAELS PARK',
  'TWEDDLE PLACE',
  'MILL WOODS TOWN CENTRE',
  'EKOTA',
  'LEE RIDGE',
  'WALKER',
  'EDMONTON SOUTH CENTRAL EAST'],
 'Métis Ward': ['EASTGATE BUSINESS PARK',
  'WEIR INDUSTRIAL',
  'MONTROSE',
  'CROMDALE',
  'ELMWOOD PARK',
  'ALBERTA AVENUE',
  'RUNDLE HEIGHTS',
  'BONNIE DOON',
  'EASTWOOD',
  'NEWTON',
  'INDUSTRIAL HEIGHTS',
  'BEVERLY HEIGHTS',
  'KING EDWARD PARK',
  'MORRIS INDUSTRIAL',
  'RIVER VALLEY HIGHLANDS',
  'TERRACE HEIGHTS',
  'DAVIES INDUSTRIAL WEST',
  'FOREST HEIGHTS',
  'HIGHLANDS',
  'CLOVERDALE',
  'OTTEWELL',
  'AVONMORE',
  'DELTON',
  'DAVIES INDUSTRIAL EAST',
  'KENILWORTH',
  'IDYLWYLDE',
  'GOLD BAR',
  'BEACON HEIGHTS',
  'RIVER VALLEY RIVERSIDE',
  'BERGMAN',
  'RIVER VALLEY GOLD BAR',
  'YELLOWHEAD CORRIDOR EAST',
  'BELLEVUE',
  'RIVER VALLEY KINNAIRD',
  'PARKDALE',
  'STRATHEARN',
  'CAPILANO',
  'GIRARD INDUSTRIAL',
  'VIRGINIA PARK',
  'FULTON PLACE',
  'EDMONTON NORTHLANDS',
  'GAINER INDUSTRIAL',
  'HOLYROOD',
  'LAMBTON INDUSTRIAL',
  'ABBOTTSFIELD',
  'RIVER VALLEY RUNDLE'],
 'Nakota Isga Ward': ['GLENWOOD',
  'WEST JASPER PLACE',
  'ALDERGROVE',
  'WINTERBURN INDUSTRIAL AREA EAST',
  'LA PERLE',
  'BRITANNIA YOUNGSTOWN',
  'WINTERBURN INDUSTRIAL AREA WEST',
  'YOUNGSTOWN INDUSTRIAL',
  'MCNAMARA INDUSTRIAL',
  'KINOKAMAU PLAINS AREA',
  'SECORD',
  'SHEFFIELD INDUSTRIAL',
  'STARLING',
  'GLENORA',
  'HAWKS RIDGE',
  'WILSON INDUSTRIAL',
  'PINTAIL LANDING',
  'TRUMPETER AREA',
  'CANORA',
  'GROVENOR',
  'KINGLET GARDENS',
  'EDMISTON INDUSTRIAL',
  'LEWIS FARMS INDUSTRIAL',
  'MORIN INDUSTRIAL',
  'RIVER VALLEY GLENORA',
  'STONE INDUSTRIAL',
  'PLACE LARUE',
  'ANTHONY HENDAY BIG LAKE',
  'ANTHONY HENDAY',
  'ROSENTHAL',
  'POTTER GREENS',
  'STEWART GREENS',
  'SUDER GREENS',
  'WESTVIEW VILLAGE',
  'WEBBER GREENS',
  'HAWIN PARK ESTATE INDUSTRIAL',
  'ARMSTRONG INDUSTRIAL',
  'ALBERTA PARK INDUSTRIAL',
  'WHITE INDUSTRIAL',
  'SUNWAPTA INDUSTRIAL',
  'WEST SHEFFIELD INDUSTRIAL',
  'MCQUEEN',
  'BELMEAD',
  'CRESTWOOD',
  'HIGH PARK',
  'MAYFIELD',
  'NORWESTER INDUSTRIAL',
  'CARLETON SQUARE INDUSTRIAL',
  'NORTH GLENORA',
  'TERRA LOSA',
  'BRECKENRIDGE GREENS',
  'POUNDMAKER INDUSTRIAL'],
 "O-day'min Ward": ['OLIVER',
  'CENTRAL MCDOUGALL',
  'WESTMOUNT',
  'QUEEN MARY PARK',
  'BOYLE STREET',
  'PRINCE RUPERT',
  'SPRUCE AVENUE',
  'RIVERDALE',
  'DOWNTOWN',
  'MCCAULEY',
  'WESTWOOD',
  'RIVER VALLEY VICTORIA',
  'BLATCHFORD AREA',
  'ROSSDALE',
  'RIVER VALLEY WALTERDALE'],
 'Sspomitapi Ward': ['MAPLE RIDGE',
  'BISSET',
  'WEINLOS',
  'POLLARD MEADOWS',
  'SOUTHEAST INDUSTRIAL',
  'KINISKI GARDENS',
  'DALY GROVE',
  'CRAWFORD PLAINS',
  'MELTWATER',
  'ASTER',
  'DECOTEAU',
  'LARKSPUR',
  'MINCHAU',
  'TAMARACK',
  'MAPLE RIDGE INDUSTRIAL',
  'DECOTEAU NORTH',
  'LAUREL',
  'ANTHONY HENDAY SOUTH EAST',
  'PYLYPOW INDUSTRIAL',
  'MAPLE',
  'SILVER BERRY',
  'JACKSON HEIGHTS',
  'WILD ROSE',
  'EDMONTON SOUTH EAST'],
 'papastew Ward': ['STRATHCONA',
  'QUEEN ALEXANDRA',
  'GARNEAU',
  'EMPIRE PARK',
  'RITCHIE',
  'LANSDOWNE',
  'CORONET INDUSTRIAL',
  'GREENFIELD',
  'CPR IRVINE',
  'MALMO PLAINS',
  'GRANDVIEW HEIGHTS',
  'WINDSOR PARK',
  'ALLENDALE',
  'STRATHCONA JUNCTION',
  'UNIVERSITY OF ALBERTA',
  'HAZELDEAN',
  'MILL CREEK RAVINE NORTH',
  'BELGRAVIA',
  'PLEASANTVIEW',
  'ROYAL GARDENS',
  'DUGGAN',
  'RIDEAU PARK',
  'ASPEN GARDENS',
  'MCKERNAN',
  'CALGARY TRAIL NORTH',
  'CORONET ADDITION INDUSTRIAL',
  'WHITEMUD CREEK RAVINE SOUTH',
  'PARKALLEN',
  'UNIVERSITY OF ALBERTA FARM',
  'BROOKSIDE',
  'MILL CREEK RAVINE SOUTH',
  'RIVER VALLEY WHITEMUD',
  'ROSEDALE INDUSTRIAL',
  'LENDRUM PLACE',
  'WESTBROOK ESTATES',
  'RIVER VALLEY MAYFAIR',
  'WHITEMUD CREEK RAVINE NORTH',
  'ARGYLL'],
 'pihêsiwin Ward': ['RAMSAY HEIGHTS',
  'HENDERSON ESTATES',
  'RHATIGAN RIDGE',
  'WINDERMERE',
  'WINDERMERE AREA',
  'SOUTH TERWILLEGAR',
  'KESWICK AREA',
  'CARTER CREST',
  'OGILVIE RIDGE',
  'RIVER VALLEY WINDERMERE',
  'RIVER VALLEY TERWILLEGAR',
  'ANTHONY HENDAY TERWILLEGAR',
  'HADDOW',
  'GLENRIDDING HEIGHTS',
  'AMBLESIDE',
  'WHITEMUD CREEK RAVINE TWIN BROOKS',
  'BULYEA HEIGHTS',
  'BRANDER GARDENS',
  'FALCONER HEIGHTS',
  'RIVER VALLEY FORT EDMONTON',
  'MACTAGGART',
  'LEGER',
  'TERWILLEGAR TOWNE',
  'HODGSON',
  'MAGRATH HEIGHTS',
  'EDMONTON SOUTH WEST'],
 'sipiwiyiniwak Ward': ['RIO TERRACE',
  'WESTRIDGE',
  'MEADOWLARK PARK',
  'JASPER PARK',
  'RIVER VALLEY OLESKIW',
  'WEST MEADOWLARK PARK',
  'SHERWOOD',
  'CALLINGWOOD SOUTH',
  'LYMBURN',
  'ELMWOOD',
  'JAMIESON PLACE',
  'LYNNWOOD',
  'PATRICIA HEIGHTS',
  'RIVER VALLEY LESSARD NORTH',
  'SUMMERLEA',
  'ORMSBY PLACE',
  'RIVERVIEW AREA',
  'OLESKIW',
  'GLASTONBURY',
  'THE UPLANDS',
  'DECHENE',
  'EDGEMONT',
  "RIVER'S EDGE",
  'WEDGEWOOD HEIGHTS',
  'RIVER VALLEY CAMERON',
  'GRANVILLE',
  'CAMERON HEIGHTS',
  'PARKVIEW',
  'DONSDALE',
  'RIVER VALLEY LAURIER',
  'ANTHONY HENDAY SOUTH WEST',
  'GARIEPY',
  'STILLWATER',
  'LAURIER HEIGHTS',
  'THE HAMPTONS',
  'CALLINGWOOD NORTH',
  'QUESNELL HEIGHTS',
  'THORNCLIFF',
  'RIVER VALLEY CAPITOL HILL'],
 'tastawiyiniwak Ward': ['BELLE RIVE',
  'BEAUMARIS',
  'LAGO LINDO',
  'KILKENNY',
  'BALWIN',
  'MAYLIEWAN',
  'EVANSDALE',
  'BATURYN',
  'KILLARNEY',
  'EAUX CLAIRES',
  'ANTHONY HENDAY CASTLEDOWNS',
  'LORELEI',
  'ELSINORE',
  'KILDARE',
  'OZERNA',
  'NORTHMOUNT',
  'KLARVATTEN',
  'GLENGARRY',
  'CRYSTALLINA NERA EAST',
  'ANTHONY HENDAY LAKE DISTRICT',
  'DELWOOD',
  'CRYSTALLINA NERA WEST',
  'CHAMBERY',
  'SCHONSEE']}

In [28]:
ward_dict['Dene Ward']

['RURAL NORTH EAST HORSE HILL',
 'FRASER',
 'BANNERMAN',
 'HAIRSINE',
 'BELVEDERE',
 'CLOVER BAR AREA',
 'CASSELMAN',
 'EDMONTON ENERGY AND TECHNOLOGY PARK',
 'RURAL NORTH EAST SOUTH STURGEON',
 'KIRKNESS',
 'ANTHONY HENDAY HORSE HILL',
 'YORK',
 'EBBERS',
 'HOMESTEADER',
 'MARQUIS',
 'GORMAN',
 'KENNEDALE INDUSTRIAL',
 'CY BECKER',
 'MCCONACHIE AREA',
 'BRINTNELL',
 'ANTHONY HENDAY ENERGY PARK',
 'OVERLANDERS',
 'EVERGREEN',
 'ANTHONY HENDAY CLAREVIEW',
 'MCLEOD',
 'MATT BERRY',
 'HOLLICK-KENYON',
 'KERNOHAN',
 'RIVER VALLEY HERMITAGE',
 'CLAREVIEW TOWN CENTRE',
 'BELMONT',
 'CANON RIDGE',
 'SIFTON PARK',
 'MILLER']

In [29]:
test = 'BEARSPAW'
for index, value in enumerate(ward_dict.values()):
    if test in value:   
        print(list(ward_dict)[index])
    else:
        print('no')

no
no
Ipiihkoohkanipiaohtsi Ward
no
no
no
no
no
no
no
no
no

In [30]:
list(ward_dict)[2]

'Ipiihkoohkanipiaohtsi Ward'

In [71]:
def nbhd_fill(row):
    for index, value in enumerate(ward_dict.values()):
        if row['Neighbourhood'] in value:
#             print(list(ward_dict)[index])
#             print(row['Ward'])
            row['Ward'] = list(ward_dict)[index]
    return row['Ward']

In [72]:
resi_house_data['Ward'] = 0
resi_house_data.head()

C:\Users\mitch\AppData\Local\Temp/ipykernel_8652/2032237380.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resi_house_data['Ward'] = 0

,Account Number,Assessment Year,Suite,House Number,Street Name,Legal Description,Latitude,Longitude,Point Location,Neighbourhood,...,Zoning,Lot Size,Assessed Value,Assessment Class 1,Assessment Class % 1,Assessment Class 2,Assessment Class % 2,Assessment Class 3,Assessment Class % 3,Ward
0,1068451,2015,NaN,4007.000000,SAVARYN DRIVE SW,SW 22-51-24-4,NaN,NaN,NaN,SUMMERSIDE,...,RPL,109314.321000,7597000.000000,RESIDENTIAL,100.000000,NaN,NaN,NaN,NaN,0
7,1650860,2014,NaN,NaN,NaN,Plan: 3782RS Block: 1 Lot: 30U,53.515450,-113.616270,POINT (-113.61627 53.51545),THORNCLIFF,...,RF1,118.072000,0.000000,RESIDENTIAL,100.000000,NaN,NaN,NaN,NaN,0
9,2914836,2018,NaN,13004.000000,115 AVENUE NW,Plan: 1568HW Block: 4 Lot: 21,NaN,NaN,NaN,INGLEWOOD,...,RF3,490.277000,358500.000000,RESIDENTIAL,100.000000,NaN,NaN,NaN,NaN,0
14,3169893,2019,NaN,2503.000000,101 STREET SW,Plan: 8721140 Block: E,NaN,NaN,NaN,ELLERSLIE INDUSTRIAL,...,AGI,49452.501000,244500.000000,RESIDENTIAL,100.000000,NaN,NaN,NaN,NaN,0
28,9947689,2013,NaN,35.000000,ELSINORE PLACE NW,NE 5-54-24-4,NaN,NaN,NaN,ELSINORE,...,RF1,711.319000,55500.000000,RESIDENTIAL,100.000000,NaN,NaN,NaN,NaN,0

In [73]:
nbhd_fill(resi_house_data.iloc[0,:])

c:\users\mitch\documents\data science side projects\edmonton property dashboard\prop_env\lib\site-packages\pandas\core\series.py:1056: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()

'Karhiio Ward'

In [74]:
resi_house_data['Ward'].iloc[0,:] = 1
resi_house_data.iloc[0,:]['Ward']

c:\users\mitch\documents\data science side projects\edmonton property dashboard\prop_env\lib\site-packages\pandas\core\indexing.py:1951: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[selected_item_labels] = value

1

In [75]:
resi_house_data['Ward'] = 0
resi_house_data['Ward'] = resi_house_data.apply(nbhd_fill, axis=1)

C:\Users\mitch\AppData\Local\Temp/ipykernel_8652/4122748853.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resi_house_data['Ward'] = 0
C:\Users\mitch\AppData\Local\Temp/ipykernel_8652/4122748853.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resi_house_data['Ward'] = resi_house_data.apply(nbhd_fill, axis=1)

In [77]:
resi_house_data['Ward'].value_counts()

O-day'min Ward                294918
sipiwiyiniwak Ward            293127
Métis Ward                    292853
pihêsiwin Ward                265399
Dene Ward                     263119
Ipiihkoohkanipiaohtsi Ward    258105
Karhiio Ward                  255839
Anirniq Ward                  251399
papastew Ward                 250785
tastawiyiniwak Ward           249039
Nakota Isga Ward              247808
Sspomitapi Ward               213862
0                              22790
Name: Ward, dtype: int64

Still some missing wards in the ward column, lets check out

In [79]:
no_ward_mask = resi_house_data[resi_house_data['Ward'] == 0]

In [80]:
no_ward_mask['Neighbourhood'].value_counts()

RAPPERSWIL                          8159
TERWILLEGAR SOUTH                   4515
GLENRIDDING AREA                    3950
WESTBROOK ESTATE                    3030
RURAL WEST                           565
RURAL WEST BIG LAKE                  458
CRYSTALLINA NERA                     457
MAGRATH HEIGHTS AREA                 373
RURAL SOUTH EAST                     317
ANTHONY HENDAY SOUTHEAST             292
PILOT SOUND AREA WEST PORTION        186
RURAL NORTH EAST NORTH STURGEON      138
MACTAGGART AREA                      122
SOUTHEAST (ANNEXED) INDUSTRIAL        97
MEADOWS AREA                          61
RIVER VALLEY WINDEMERE                46
HERITAGE VALLEY AREA EAST              8
PLACE LA RUE                           6
RURAL WEST LEWIS FARMS                 5
MILL CREEK RAVINE                      2
LAKE DISTRICT NORTH EAST PORTION       1
CPR WEST                               1
RURAL NORTH WEST                       1
Name: Neighbourhood, dtype: int64

Rapperswil should be in Anirniq Ward?

In [83]:
ward_dict['Anirniq Ward']

['ALBANY',
 'ANTHONY HENDAY MISTATIM',
 'ANTHONY HENDAY RAMPART',
 'ATHLONE',
 'BARANOW',
 'BONAVENTURE INDUSTRIAL',
 'BROWN INDUSTRIAL',
 'CAERNARVON',
 'CALDER',
 'CANOSSA',
 'CARLISLE',
 'CARLTON',
 'CUMBERLAND',
 'DOMINION INDUSTRIAL',
 'DOVERCOURT',
 'DUNLUCE',
 'GAGNON ESTATE INDUSTRIAL',
 'GARSIDE INDUSTRIAL',
 'GOODRIDGE CORNERS',
 'GRIESBACH',
 'HAGMANN ESTATE INDUSTRIAL',
 'HIGH PARK INDUSTRIAL',
 'HUDSON',
 'HUFF BREMNER ESTATE INDUSTRIAL',
 'INGLEWOOD',
 'KENSINGTON',
 'LAUDERDALE',
 'MCARTHUR INDUSTRIAL',
 'MISTATIM INDUSTRIAL',
 'MITCHELL INDUSTRIAL',
 'OXFORD',
 'PEMBINA',
 'PRINCE CHARLES',
 'RAMPART INDUSTRIAL',
 'RAPPERSWILL',
 'ROSSLYN',
 'SHERBROOKE',
 'WELLINGTON',
 'WOODCROFT',
 'YELLOWHEAD CORRIDOR WEST']

Rapperswil is misspelt, should be Rapperswill. This continues with other neighbourhoods as well, many neighbourhoods have word "area" with it, causing the dictionary map to not work. Lets continue cleaning.